[#ftl]
[@b.head/]
[@b.toolbar title="新增/修改年度批次"]bar.addBack();[/@]
[@b.tabs]
  [@b.form theme="list" action=b.rest.save(batch)]
    [@b.textfield name="batch.name" label="名称" value="${batch.name!}" required="true" maxlength="80"/]
    [#list stageTypes?sort_by('indexno') as stageType]
     [#assign stage=batch.getStage(stageType)!/]
    [@b.startend label=stageType.name
      name="stageType"+stageType.id+".beginAt,stageType"+stageType.id+".endAt" required="false,false"
      start=(stage.beginAt)! end=(stage.endAt)! format="datetime" style="width:150px"/]
    [/#list]
    [#list stageTypes?sort_by('indexno') as stageType]
     [#assign stage=batch.getStage(stageType)!/]
    [@b.textfield label=stageType.name+"通知"
      name="stageType_noticeHref"+stageType.id required="false" value=(stage.noticeHref)! style="width:300px" comment="URL网址"/]
    [/#list]
    [@b.radios label="是否归档"  name="batch.archived" value=batch.archived items="1:common.yes,0:common.no"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]
