[#ftl]
[@b.head/]
[@b.toolbar title="新增/修改年度批次"]bar.addBack();[/@]
[@b.tabs]
  [@b.form theme="list" action=b.rest.save(batch)]
    [@b.textfield name="batch.name" label="名称" value="${batch.name!}" required="true" maxlength="80"/]
    [#list stageTypes as stageType]
     [#assign stage=batch.getStage(stageType)!/]
    [@b.startend label=stageType.name
      name="stageType"+stageType.id+".beginOn,stageType"+stageType.id+".endOn" required="false,false"
      start=(stage.beginOn)! end=(stage.endOn)! format="date"/]
    [/#list]
    [@b.radios label="是否归档"  name="batch.archived" value=batch.archived items="1:common.yes,0:common.no"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]
[@b.foot/]
