[#ftl]
[@b.head/]
[@b.toolbar title="新增/修改答辩组"]bar.addBack();[/@]
  [@b.form theme="list" action=b.rest.save(promotionDefenseGroup)]
    [@b.textfield name="promotionDefenseGroup.name" label="组名" value=promotionDefenseGroup.name! required="true" maxlength="80" style="width:200px;"/]
    [@b.date name="promotionDefenseGroup.defenseOn" label="答辩日期" value=promotionDefenseGroup.defenseOn!  required="true"/]
    [@b.date name="promotionDefenseGroup.beginAt" label="答辩开始时间" value=promotionDefenseGroup.beginAt!  required="true" format="HH:mm"/]
    [@b.date name="promotionDefenseGroup.endAt" label="答辩结束时间" value=promotionDefenseGroup.endAt!  required="true" format="HH:mm"/]
    [@b.textfield name="promotionDefenseGroup.location" label="答辩地点" value=promotionDefenseGroup.location!  required="true" maxlength="200" style="width:200px;"/]
    [@b.number name="promotionDefenseGroup.capacity" label="计划项目数" value=promotionDefenseGroup.capacity  required="true"/]
    [@b.formfoot]
      <input name="promotionDefenseGroup.batch.id" value="${promotionDefenseGroup.batch.id}" type="hidden"/>
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
