[@b.nav class="nav nav-tabs nav-tabs-compact"]
  [@b.navitem href="closure-review!index"]结项评审[/@]
  [@b.navitem href="review-detail!index"]评审明细[/@]
  [@b.navitem href="review-group!index"]评审小组[/@]
[/@]